GET http://localhost:8080/drivers
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLQkdC-0YDQvtC00LjQvdCU0JgiLCJpYXQiOjE3NTAwNTI4OTksImV4cCI6MTc1MDA1Mzc5OX0.CUr3hZk4Qhxxu13po6fAIl3eJsWDK-2y87v2vM0_rZY

#POST http://localhost:8080/token
#Content-Type: application/json
#
#{
#  "username": "БородинДИ",
#  "password": "password2"
#}


