apiVersion: 1

contactPoints:
  - orgId: 1
    name: critical
    receivers:
      - uid: cp-crit-telegram
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://car-park-bot:8090/bot/alerts
          httpMethod: POST
          maxAlerts: 10
          authorization_scheme: Bearer
          authorization_credentials: $ALERTS_WEBHOOK_TOKEN
      - uid: cp-crit-email
        type: email
        disableResolveMessage: false
        settings:
          addresses: $ALERT_EMAIL
          singleEmail: false

  - orgId: 1
    name: warning
    receivers:
      - uid: cp-warn-telegram
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://car-park-bot:8090/bot/alerts
          httpMethod: POST
          maxAlerts: 10
          authorization_scheme: Bearer
          authorization_credentials: $ALERTS_WEBHOOK_TOKEN

  - orgId: 1
    name: info
    receivers:
      - uid: cp-info-email
        type: email
        disableResolveMessage: true
        settings:
          addresses: $ALERT_EMAIL

  - orgId: 1
    name: heartbeat
    receivers:
      - uid: cp-heartbeat-email
        type: email
        disableResolveMessage: true
        settings:
          addresses: $ALERT_EMAIL
