apiVersion: 1

muteTimes:
  - orgId: 1
    name: night
    time_intervals:
      - times:
          - start_time: '23:00'
            end_time: '24:00'
          - start_time: '00:00'
            end_time: '08:00'
        location: 'Europe/Moscow'
